version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payslip
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network

  app:
    build:
      context: .  # Path to the directory containing the Dockerfile
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: payslip
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
  
  volumes:
  mysql-data:  # Define volumes here

  cristoplus-backend:
    container_name: payslip-backend
    build: ./
    image: payslip-backend
    command: sh -c "Java -jar payslip.jar"
    volumes:
      - ./:/code
    ports:
      - 8080:8080
    depends_on:
      - payslip